FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install --assume-yes software-properties-common \
    && add-apt-repository ppa:ondrej/php \
    && apt-get update \
    && apt-get install --assume-yes apt-utils poppler-utils \
    && apt-get install -y \
    openssl ca-certificates \
    git \
    curl \
    mysql-client libmagickwand-dev --no-install-recommends \
    nginx \
    php7.4-fpm \
    php7.4-mysql php7.4-sqlite3 php7.4-mbstring php7.4-simplexml php7.4-soap php7.4-xml \
    php7.4-zip php7.4-json php7.4-gd php7.4-curl php7.4-xdebug \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && apt-get clean

ENV COMPOSER_ALLOW_SUPERUSER 1

EXPOSE 80 443

CMD service php7.4-fpm start && nginx -g "daemon off;"
